"use client";
import { useState } from "react";
import { configureDocumentTemplate, discoverTemplatePlaceholders, getTemplateMappings } from "@/lib/document-templates/actions";
import type { DocumentTemplate } from "@/lib/document-templates/types";
import { TEMPLATE_VARIABLES } from "@/lib/document-templates/types";

export function TemplateConfigureDialog({ template }: { template: DocumentTemplate }) {
  const [open, setOpen] = useState(false); const [placeholders, setPlaceholders] = useState<string[]>([]); const [mapping, setMapping] = useState<Record<string,string>>({}); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function autoMap(keys: string[]) { const next: Record<string, string> = {}; for (const key of keys) { const exact = TEMPLATE_VARIABLES.find((item) => item.key === key || item.sourcePath === key); if (exact) next[key] = exact.key; } setMapping(next); }
  async function openDialog() { setOpen(true); setBusy(true); const result = await discoverTemplatePlaceholders(template.id); const detected = result.data.length ? result.data : ["seller.legal_name", "buyer.legal_name", "contract.number", "product.name", "product.quantity", "product.unit_price", "product.amount"]; setPlaceholders(detected); autoMap(detected); const saved = await getTemplateMappings(template.id); if (saved.data.length) { setPlaceholders(saved.data.map((item) => item.placeholder)); setMapping(Object.fromEntries(saved.data.map((item) => [item.placeholder, item.sky_variable ?? ""]))); } setMessage(result.error && result.data.length ? result.error : saved.error); setBusy(false); }
  async function save() { setBusy(true); const result = await configureDocumentTemplate({ templateId: template.id, mappings: placeholders.map((placeholder) => ({ placeholder, skyVariable: mapping[placeholder] ?? null, isRepeatingProductRow: placeholder.startsWith("product.") })) }); setMessage(result.success ? "Configuration saved. Template is Ready." : result.error); setBusy(false); if (result.success) setOpen(false); }
  return <><button type="button" onClick={openDialog} className="rounded-md border border-sky-500/30 px-2 py-1 text-xs text-sky-300">Configure</button>{open ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-xl border border-border bg-background p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Configure Template</h2><p className="text-xs text-muted-foreground">{template.name} · {template.document_type} · v{template.version}</p></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className="mt-4 max-h-80 space-y-2 overflow-auto">{busy && !placeholders.length ? <p className="text-sm text-muted-foreground">Detecting placeholders…</p> : placeholders.length ? placeholders.map((placeholder) => <div key={placeholder} className="grid grid-cols-2 items-center gap-2"><code className="rounded bg-muted px-2 py-1 text-xs">&#123;&#123;{placeholder}&#125;&#125;</code><select value={mapping[placeholder] ?? ""} onChange={(event) => setMapping((current) => ({ ...current, [placeholder]: event.target.value }))} className="rounded border border-border bg-background px-2 py-1 text-sm"><option value="">Select SKY field</option>{TEMPLATE_VARIABLES.map((variable) => <option key={variable.key} value={variable.key}>{variable.label}</option>)}</select></div>) : <p className="text-sm text-muted-foreground">No placeholders detected. Add placeholders to the DOCX or configure fields manually.</p>}</div>{message ? <p className="mt-3 text-sm text-muted-foreground">{message}</p> : null}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={openDialog} className="rounded border border-border px-3 py-2 text-sm">Detect Again</button><button type="button" disabled={busy} onClick={save} className="rounded bg-foreground px-3 py-2 text-sm text-background">Save Configuration</button></div></div></div> : null}</>;
}
