"use client";
import { useState } from "react";
import type { DocumentTemplate } from "@/lib/document-templates/types";

export function TemplateTestGenerateButton({ template }: { template: DocumentTemplate }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function run() { setBusy(true); setMessage(null); try { const response = await fetch("/api/documents/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ templateId: template.id, documentType: template.document_type === "invoice" ? "invoice" : template.document_type, data: { contract: { number: "TEST-2026-001", date: "2026-09-03", currency: "USD", incoterms: "FOB" }, seller: { legal_name: "ALTAY FISH LLC" }, buyer: { legal_name: "MAREX CARGO CO., LTD" }, consignee: { legal_name: "Test Consignee" }, products: [{ name: "FROZEN FRESH SHRIMP 2L", quantity: 10, unit: "kg", unit_price: 12, amount: 120 }, { name: "FROZEN FRESH SHRIMP L/A", quantity: 20, unit: "kg", unit_price: 13, amount: 260 }, { name: "FROZEN FRESH SHRIMP 3L", quantity: 30, unit: "kg", unit_price: 14, amount: 420 }] } }) }); if (!response.ok) { const payload = await response.json().catch(() => null) as { error?: string } | null; throw new Error(payload?.error ?? "Test generation failed."); } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `test-${template.document_type}.docx`; anchor.click(); URL.revokeObjectURL(url); setMessage("Test DOCX generated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Test generation failed."); } finally { setBusy(false); } }
  return <span className="inline-flex items-center gap-2"><button type="button" onClick={run} disabled={busy} className="rounded-md border border-emerald-500/30 px-2 py-1 text-xs text-emerald-300">{busy ? "Generating…" : "Test Generate"}</button>{message ? <span className="text-xs text-muted-foreground">{message}</span> : null}</span>;
}
