-- =============================================================================
-- PROPOSAL ONLY — Auth / Authorization / Company / Audit foundation
-- =============================================================================
-- STATUS: Documentation migration. Performs NO schema privilege or table changes.
-- DO NOT treat this file as an applied auth implementation.
--
-- Spec documents:
--   management/AUTH_SYSTEM.md
--   management/ROLE_MODEL.md
--   management/PERMISSION_MATRIX.md
--   management/COMPANY_MODEL.md
--   management/AUDIT_LOG_MODEL.md
--
-- BLOCKERS before a real (executable) follow-up migration:
--   1. Explicit user approval for authentication changes
--   2. Login/session middleware design accepted
--   3. Decision on products.company_id (per-company vs shared catalog)
--   4. Live inventory of assumed masters (contracts, counterparties, products, …)
--   5. Plan to move app off anon/publishable-key open RLS (see 20260805060000)
--
-- When approved, create a NEW timestamped migration that executes the DDL below
-- (copy out of comments). Do not edit this file into a silent apply.
-- =============================================================================

do $$
begin
  raise notice
    'AUTH FOUNDATION PROPOSAL: no tables/policies changed. See management/AUTH_SYSTEM.md and comments in 20260805070000_auth_foundation_proposal.sql';
end $$;

-- -----------------------------------------------------------------------------
-- PROPOSED DDL (COMMENTED — NOT EXECUTED)
-- -----------------------------------------------------------------------------

-- create table if not exists public.company_memberships (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users (id) on delete cascade,
--   company_id uuid not null references public.companies (id) on delete cascade,
--   role_code text not null references public.roles (code),
--   counterparty_id uuid null references public.counterparties (id) on delete set null,
--   is_active boolean not null default true,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   created_by uuid null references auth.users (id) on delete set null,
--   updated_by uuid null references auth.users (id) on delete set null,
--   unique (user_id, company_id)
-- );
-- create index if not exists company_memberships_company_id_idx on public.company_memberships (company_id);
-- create index if not exists company_memberships_user_id_idx on public.company_memberships (user_id);

-- insert into public.roles (code, name, permissions) values
--   ('platform_admin', 'Platform Admin', '["*"]'::jsonb),
--   ('company_owner', 'Company Owner', '[]'::jsonb),
--   ('general_director', 'General Director', '[]'::jsonb),
--   ('commercial_director', 'Commercial Director', '[]'::jsonb),
--   ('sales_manager', 'Sales Manager', '[]'::jsonb),
--   ('purchasing_manager', 'Purchasing Manager', '[]'::jsonb),
--   ('logistics_manager', 'Logistics Manager', '[]'::jsonb),
--   ('warehouse_manager', 'Warehouse Manager', '[]'::jsonb),
--   ('finance_manager', 'Finance Manager', '[]'::jsonb),
--   ('accountant', 'Accountant', '[]'::jsonb),
--   ('legal', 'Legal', '[]'::jsonb),
--   ('operator', 'Operator', '[]'::jsonb),
--   ('read_only', 'Read Only', '["*.read"]'::jsonb),
--   ('external_customer', 'External Customer', '[]'::jsonb),
--   ('external_supplier', 'External Supplier', '[]'::jsonb)
-- on conflict (code) do nothing;

-- -- Ownership columns (nullable first). Skip tables that already have company_id.
-- alter table public.warehouse_locations add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.inventory add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.inventory_lots add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.stock_movements add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.warehouse_transfers add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.inventory_reservations add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.shipments add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.contract_products add column if not exists company_id uuid references public.companies (id) on delete restrict;
-- alter table public.contract_imports add column if not exists company_id uuid references public.companies (id) on delete set null;
-- alter table public.activity_log add column if not exists company_id uuid references public.companies (id) on delete set null;
-- alter table public.timeline_events add column if not exists company_id uuid references public.companies (id) on delete set null;
-- alter table public.notifications add column if not exists company_id uuid references public.companies (id) on delete set null;

-- alter table public.warehouse_locations add column if not exists created_by uuid references auth.users (id) on delete set null;
-- alter table public.warehouse_locations add column if not exists updated_by uuid references auth.users (id) on delete set null;
-- -- (repeat actor columns for other operational tables in the executable migration)

-- create table if not exists public.audit_events (
--   id uuid primary key default gen_random_uuid(),
--   occurred_at timestamptz not null default now(),
--   actor_user_id uuid null references auth.users (id) on delete set null,
--   actor_email text null,
--   company_id uuid null references public.companies (id) on delete set null,
--   event_type text not null,
--   entity_type text null,
--   entity_id uuid null,
--   summary text not null,
--   metadata jsonb not null default '{}'::jsonb,
--   ip_hash text null,
--   user_agent text null,
--   request_id text null
-- );
-- create index if not exists audit_events_occurred_at_idx on public.audit_events (occurred_at desc);
-- create index if not exists audit_events_company_id_idx on public.audit_events (company_id);
-- create index if not exists audit_events_event_type_idx on public.audit_events (event_type);
-- create index if not exists audit_events_entity_idx on public.audit_events (entity_type, entity_id);

-- alter table public.company_memberships enable row level security;
-- alter table public.audit_events enable row level security;
-- -- Policies: authenticated + membership checks ONLY after app auth is live.
-- -- Do not add using(true) policies in the executable follow-up.
